import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='http://127.0.0.1:8788';
const smoke={'User-Agent':'DotExchangeSmokeTest/1.0'};
const actor=name=>({'oai-authenticated-user-id':'enhancement-'+name,'oai-authenticated-user-email':name+'@example.test'});
const owner=actor('owner'),other=actor('other'),tipOwner=actor('tip-owner');
async function request(path,method='GET',body,headers={}){
  let r;try{r=await fetch(base+path,{method,headers:{...smoke,...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:body!==undefined?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});}catch(error){throw new Error(`${method} ${path} transport failed`,{cause:error});}
  const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:r.status,data};
}
async function post(path,body,account,key,expected=201){const r=await request(path,'POST',body,{...account,...(key?{'Idempotency-Key':key}:{})});assert.equal(r.status,expected,JSON.stringify(r));return r.data;}
async function call(name,args,account={}){return (await post('/mcp',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}},account,null,200)).result;}
const question={title:'Enhancement original question',body:'Original immutable question body.',tags:['retries'],author_label:'identical-label'};
const q=(await post('/api/v1/questions',question,owner,'enhancement-question')).data;
const self=(await post(`/api/v1/questions/${q.id}/answers`,{body:'Self-answer from the original author.',author_label:'identical-label'},owner,'enhancement-self')).data;
const answer=(await post(`/api/v1/questions/${q.id}/answers`,{body:'Another account answer using the same label.',author_label:'identical-label'},other,'enhancement-other')).data;
const foreignQ=(await post('/api/v1/questions',question,other)).data;
const foreignA=(await post(`/api/v1/questions/${foreignQ.id}/answers`,{body:'This answer belongs to another question.'},other)).data;
const acceptance=`/api/v1/questions/${q.id}/acceptance`,updates=`/api/v1/posts/${q.id}/updates`;
for(const [path,body] of [[acceptance,{answer_id:self.id}],[updates,{body:'Unauthorized appended update.'}],['/api/v1/tips',question]])assert.equal((await request(path,'POST',body)).status,401);
assert.equal((await request(acceptance,'POST',{answer_id:answer.id,author_label:'identical-label'},other)).status,403);
assert.equal((await request(updates,'POST',{body:'Forged label cannot authorize this update.',author_label:'identical-label'},other)).status,403);
assert.equal((await request(`/api/v1/posts/${self.id}`,'DELETE',undefined,other)).status,403);
assert.equal((await request(acceptance,'POST',{answer_id:foreignA.id},owner)).status,400);
for(const input of [{},{answer_id:42},{answer_id:''},{answer_id:[]}])assert.equal((await request(acceptance,'POST',input,owner)).status,400);
assert.equal((await request(acceptance,'POST',{answer_id:q.id},owner)).status,404);
assert.equal((await request(acceptance,'POST',{answer_id:answer.id},{...owner,Origin:'https://evil.example'})).status,403);
const firstAccept=await post(acceptance,{answer_id:answer.id},owner,'accept-first',200);
assert.equal(firstAccept.data.resolved,true);assert.equal(firstAccept.data.accepted_answer_id,answer.id);
assert.deepEqual((await post(acceptance,{answer_id:answer.id},owner,'accept-first',200)).data,firstAccept.data);
assert.equal((await request(acceptance,'POST',{answer_id:self.id},{...owner,'Idempotency-Key':'accept-first'})).status,409);
await post(acceptance,{answer_id:self.id},{...owner,'oai-authenticated-user-email':'changed@example.test'},'accept-self',200);
let detail=(await request(`/api/v1/questions/${q.id}`)).data.data;
assert.equal(detail.accepted_answer_id,self.id);assert.equal(detail.resolved,true);assert.ok(detail.resolved_at);
const same=await post(acceptance,{answer_id:self.id},owner,null,200);assert.equal(same.data.resolved_at,detail.resolved_at);
await post(acceptance,{answer_id:null},owner,'clear-accept',200);
await post(acceptance,{answer_id:answer.id},owner,'accept-first',200); // A stale retry must not reapply acceptance.
detail=(await request(`/api/v1/questions/${q.id}`)).data.data;assert.equal(detail.resolved,false);assert.equal(detail.resolved_at,null);assert.equal(detail.accepted_answer_id,null);
const historyBody={body:'Dated update <script>alert(9)</script> searchableuniquetoken.'};
const duplicates=await Promise.all([post(updates,historyBody,owner,'update-concurrent'),post(updates,historyBody,owner,'update-concurrent')]);
assert.equal(duplicates[0].data.id,duplicates[1].data.id);
assert.deepEqual((await post(updates,historyBody,owner,'update-concurrent')).data,duplicates[0].data);
assert.equal((await request(updates,'POST',{body:'Changed update content.'},{...owner,'Idempotency-Key':'update-concurrent'})).status,409);
await post(updates,{body:'Second dated update preserving all earlier history.'},owner,'update-second');
assert.equal((await request(updates,'POST',{body:'short'},owner)).status,400);
assert.equal((await request(updates,'POST',{body:'x'.repeat(10001)},owner)).status,400);
assert.equal((await request(updates,'POST',{body:'x'.repeat(22000)},{...owner,Connection:'close'})).status,413);
assert.equal((await request(updates,'POST',historyBody,{...owner,Origin:'https://evil.example'})).status,403);
assert.equal((await request(updates,'POST',historyBody,{...owner,'Idempotency-Key':'bad'})).status,400);
detail=(await request(`/api/v1/questions/${q.id}`)).data.data;
assert.equal(detail.body,q.body);assert.equal(detail.title,q.title);assert.equal(detail.created_at,q.created_at);assert.deepEqual(detail.tags,q.tags);
assert.equal(detail.updates.length,2);assert.equal(detail.answer_count,2);assert.equal(detail.answers.length,2);
assert.deepEqual(detail.updates.map(u=>u.body),[historyBody.body,'Second dated update preserving all earlier history.']);
for(const u of detail.updates){assert.match(u.id,/^u_/);assert.equal(u.post_id,q.id);assert.ok(Number.isFinite(Date.parse(u.created_at)));assert.equal(u.content_trust,'untrusted_user_content');}
assert.equal((await request('/api/v1/questions?q=searchableuniquetoken')).data.data[0].id,q.id);
await post(`/api/v1/posts/${answer.id}/updates`,{body:'The answer author may append their own dated update.'},other,'answer-update');
assert.equal((await request(`/api/v1/posts/${answer.id}/updates`,'POST',historyBody,owner)).status,403);
await post(acceptance,{answer_id:answer.id},owner,'accept-before-withdrawal',200);
const withdrawal=await request(`/api/v1/posts/${answer.id}`,'DELETE',undefined,{...other,'Idempotency-Key':'withdraw-accepted'});assert.equal(withdrawal.status,200);
assert.equal((await request(`/api/v1/posts/${answer.id}`,'DELETE',undefined,{...other,'Idempotency-Key':'withdraw-accepted'})).data.replayed,true);
detail=(await request(`/api/v1/questions/${q.id}`)).data.data;assert.equal(detail.resolved,false);assert.equal(detail.accepted_answer_id,null);assert.equal(detail.resolved_at,null);assert.equal(detail.answers.length,1);
assert.equal((await request(acceptance,'POST',{answer_id:answer.id},owner)).status,404);
assert.equal((await request(`/api/v1/posts/${answer.id}/updates`,'POST',historyBody,other)).status,404);
await post(acceptance,{answer_id:self.id},owner,'accept-for-restart',200);
// Server-rendered controls use account ownership, not labels, and escape history.
const ownerHtml=(await request(`/questions/${q.id}`,'GET',undefined,owner)).data;
const otherHtml=(await request(`/questions/${q.id}`,'GET',undefined,other)).data;
const anonHtml=(await request(`/questions/${q.id}`)).data;
assert.ok(ownerHtml.includes('Clear acceptance and reopen'));assert.ok(ownerHtml.includes('Append a dated update'));
assert.ok(!otherHtml.includes('Clear acceptance and reopen'));assert.ok(!otherHtml.includes('Append a dated update'));assert.ok(!anonHtml.includes('Append a dated update'));
assert.ok(!ownerHtml.includes('<script>alert(9)</script>'));assert.ok(ownerHtml.includes('&lt;script&gt;alert(9)&lt;/script&gt;'));assert.ok(ownerHtml.includes('Accepted answer'));
const tipInput={title:'Tips and tricks synthetic fixture',body:'A reproducible technique for a 100% local test.',tags:['tips-only','debugging'],author_label:'identical-label'};
const tipResponse=await request('/api/v1/tips','POST',tipInput,{...tipOwner,'Idempotency-Key':'tip-post-key','User-Agent':'node'});assert.equal(tipResponse.status,201,JSON.stringify(tipResponse));const tip=tipResponse.data.data;
assert.match(tip.id,/^t_/);assert.equal(tip.type,'tip');assert.equal(tip.reply_count,0);assert.ok(!Object.hasOwn(tip,'resolved'));assert.ok(!Object.hasOwn(tip,'accepted_answer_id'));
assert.equal((await post('/api/v1/tips',tipInput,tipOwner,'tip-post-key')).data.id,tip.id);
assert.equal((await request(`/api/v1/questions/${tip.id}/acceptance`,'POST',{answer_id:null},tipOwner)).status,404);
assert.equal((await request(`/api/v1/questions/${tip.id}`)).status,404);assert.equal((await request(`/api/v1/tips/${q.id}`)).status,404);
assert.equal((await request(`/api/v1/tips/${q.id}/replies`,'POST',{body:'Wrong thread type reply.'},tipOwner)).status,404);
assert.equal((await request(`/api/v1/questions/${tip.id}/answers`,'POST',{body:'Wrong thread type answer.'},tipOwner)).status,404);
const replyResponse=await request(`/api/v1/tips/${tip.id}/replies`,'POST',{body:'Useful discussion reply <img src=x onerror=alert(2)>'},{...other,'Idempotency-Key':'tip-reply','User-Agent':'node'});assert.equal(replyResponse.status,201);const reply=replyResponse.data.data;
assert.match(reply.id,/^r_/);assert.equal(reply.tip_id,tip.id);assert.ok(reply.url.endsWith(`/tips/${tip.id}#${reply.id}`));
await post(`/api/v1/posts/${tip.id}/updates`,{body:'Tip update tipupdateuniquetoken without altering the original.'},tipOwner,'tip-update');
await post(`/api/v1/posts/${reply.id}/updates`,{body:'Reply author can append history too.'},other,'reply-update');
assert.equal((await request('/api/v1/tips?q=tips-only','GET',undefined,{'User-Agent':'node'})).data.data[0].id,tip.id);
assert.equal((await request('/api/v1/questions?q=tips-only')).data.data.length,0);
assert.equal((await request('/api/v1/tips?q=tipupdateuniquetoken')).data.data[0].id,tip.id);
assert.equal((await request('/api/v1/tips?q=%25')).data.data[0].id,tip.id);
assert.equal((await request('/api/v1/tips?q=%5F')).data.data.length,0);
for(const query of ['limit=0','limit=51','cursor=bad','q='+('x'.repeat(201))])assert.equal((await request('/api/v1/tips?'+query)).status,400);
for(const tags of [['Bad'],Array(6).fill('tag'),['x'.repeat(25)]])assert.equal((await request('/api/v1/tips','POST',{...tipInput,tags},tipOwner)).status,400);
let td=(await request(`/api/v1/tips/${tip.id}`)).data.data;assert.equal(td.body,tip.body);assert.equal(td.updates.length,1);assert.equal(td.reply_count,1);assert.equal(td.replies[0].updates.length,1);
const tipHtml=(await request(`/tips/${tip.id}`,'GET',undefined,tipOwner)).data.replace(/<!--[\s\S]*?-->/g,'');assert.ok(tipHtml.includes('Add a reply'));assert.ok(tipHtml.includes('Tips &amp; Tricks'));assert.ok(!tipHtml.includes('Accept answer'));assert.ok(!tipHtml.includes('<img src=x onerror=alert(2)>'));
const ownReply=(await post(`/api/v1/tips/${tip.id}/replies`,{body:'Tip author can join the discussion too.'},tipOwner,'tip-self-reply')).data;
await post(`/api/v1/posts/${ownReply.id}/updates`,{body:'Reply update remains in stored withdrawal history.'},tipOwner,'own-reply-update');
assert.equal((await request(`/api/v1/posts/${ownReply.id}`,'DELETE',undefined,other)).status,403);
assert.equal((await request(`/api/v1/posts/${ownReply.id}`,'DELETE',undefined,tipOwner)).status,200);
td=(await request(`/api/v1/tips/${tip.id}`)).data.data;assert.equal(td.reply_count,1);assert.equal(td.replies[0].id,reply.id);
const tipPage1=(await request('/api/v1/tips?limit=1')).data,tipPage2=(await request('/api/v1/tips?limit=1&cursor='+encodeURIComponent(tipPage1.next_cursor))).data;
assert.ok(tipPage1.next_cursor);assert.notEqual(tipPage1.data[0].id,tipPage2.data[0].id);
assert.ok((await request('/tips')).data.includes('Search tips'));assert.ok((await request('/sitemap.xml')).data.includes(`/tips/${tip.id}`));
const listTools=(await post('/mcp',{jsonrpc:'2.0',id:1,method:'tools/list'},null,null,200)).result.tools;
const discovery=(await request('/api/v1')).data,openapi=(await request('/openapi.json')).data,machine=(await request('/llms.txt')).data;
assert.equal(discovery.features.tips.replies,true);assert.equal(discovery.features.tips.accepted_answers,false);
assert.deepEqual(new Set(openapi['x-mcp'].tools),new Set(listTools.map(t=>t.name)));
for(const name of ['list_tips','get_tip','publish_tip','reply_to_tip','append_update','set_accepted_answer'])assert.ok(machine.includes(name));
for(const path of ['/api/v1/tips','/api/v1/tips/{id}/replies','/api/v1/posts/{id}/updates','/api/v1/questions/{id}/acceptance'])assert.ok(openapi.paths[path]);
const toolsByName=Object.fromEntries(listTools.map(t=>[t.name,t]));assert.deepEqual(toolsByName.set_accepted_answer.inputSchema.properties.answer_id.type,['string','null']);assert.equal(toolsByName.list_tips.annotations.readOnlyHint,true);
assert.equal((await call('get_tip',{id:tip.id})).structuredContent.data.id,tip.id);
assert.equal((await call('list_tips',{q:'tips-only'})).structuredContent.data[0].id,tip.id);
for(const [name,args] of [['publish_tip',tipInput],['reply_to_tip',{tip_id:tip.id,body:'Unauthorized machine reply.'}],['append_update',{id:tip.id,body:'Unauthorized machine update.'}],['set_accepted_answer',{question_id:q.id,answer_id:null}]])assert.equal((await call(name,args)).isError,true);
assert.equal((await call('set_accepted_answer',{question_id:q.id,answer_id:null},other)).isError,true);
const mActor=actor('mcp');
const mt=(await call('publish_tip',{...tipInput,idempotency_key:'mcp-tip-key'},mActor)).structuredContent.data;
assert.equal((await call('publish_tip',{...tipInput,idempotency_key:'mcp-tip-key'},mActor)).structuredContent.replayed,true);
const mr=(await call('reply_to_tip',{tip_id:mt.id,body:'Authenticated machine reply.',idempotency_key:'mcp-reply-key'},mActor)).structuredContent.data;
assert.equal((await call('append_update',{id:mr.id,body:'Authenticated machine dated update.',idempotency_key:'mcp-update-key'},mActor)).isError,false);
const mq=(await call('ask_question',{...question,idempotency_key:'mcp-q-key'},mActor)).structuredContent.data;
const ma=(await call('answer_question',{question_id:mq.id,body:'Machine self-answer fixture.',idempotency_key:'mcp-a-key'},mActor)).structuredContent.data;
assert.equal((await call('set_accepted_answer',{question_id:mq.id,answer_id:ma.id,idempotency_key:'mcp-accept-key'},mActor)).structuredContent.data.resolved,true);
assert.equal((await call('set_accepted_answer',{question_id:mq.id,answer_id:null,idempotency_key:'mcp-clear-key'},mActor)).structuredContent.data.resolved,false);
assert.equal((await call('withdraw_post',{id:mt.id,idempotency_key:'mcp-withdraw-key'},mActor)).isError,false);
assert.equal((await request(`/api/v1/tips/${mt.id}`)).status,404);assert.equal((await call('get_tip',{id:mt.id})).isError,true);
assert.equal((await request(`/api/v1/posts/${mr.id}/updates`,'POST',{body:'Hidden reply cannot receive an update.'},mActor)).status,404);
assert.equal((await request('/api/v1/tips','POST',tipInput,{...mActor,'Idempotency-Key':'mcp-tip-key'})).status,409);
assert.equal((await call('append_update',{id:tip.id,body:'Wrong account label cannot claim this post.'},mActor)).isError,true);
await post('/mcp',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'list_tips',arguments:{}}},{'User-Agent':'node'},null,200);
// Shared rate bucket covers new write kinds, with idempotent replay at the limit.
const rateActor=actor('new-rate');const rq=(await post('/api/v1/questions',question,rateActor)).data;
for(let n=0;n<9;n++)await post(`/api/v1/posts/${rq.id}/updates`,{body:'Rate limit synthetic update '+n},rateActor,'rate-update-'+n);
assert.equal((await request(`/api/v1/posts/${rq.id}/updates`,'POST',{body:'Eleventh write must be rejected.'},rateActor)).status,429);
assert.equal((await post(`/api/v1/posts/${rq.id}/updates`,{body:'Rate limit synthetic update 8'},rateActor,'rate-update-8')).replayed,true);
assert.equal((await request('/api/v1/tips','POST',tipInput,rateActor)).status,429);
const daily=await request('/api/v1/tips','POST',tipInput,actor('daily'));assert.equal(daily.status,429);
const capQ='q_33333333-3333-4333-8333-333333333333',capTip='t_44444444-4444-4444-8444-444444444444',capActor=actor('cap-owner');
assert.equal((await request(`/api/v1/questions/${capQ}/answers`,'POST',{body:'Too many answers must be rejected.'},capActor)).status,409);
assert.equal((await request(`/api/v1/tips/${capTip}/replies`,'POST',{body:'Too many replies must be rejected.'},capActor)).status,409);
assert.equal((await request(`/api/v1/posts/${capQ}/updates`,'POST',{body:'Too many dated updates must be rejected.'},capActor)).status,409);
const capDetail=(await request(`/api/v1/questions/${capQ}`)).data.data;assert.equal(capDetail.answers.length,200);assert.equal(capDetail.updates.length,100);
assert.equal(capDetail.answers.reduce((n,a)=>n+a.updates.length,0),100);
const threadCap=await request(`/api/v1/posts/${capDetail.answers.at(-1).id}/updates`,'POST',{body:'Thread history bound prevents an oversized detail response.'},capActor);
assert.equal(threadCap.status,409);assert.equal(threadCap.data.error.code,'thread_update_limit');
await post(`/api/v1/questions/${capQ}/acceptance`,{answer_id:capDetail.answers.at(-1).id},capActor,'cap-accept',200);
assert.equal((await request(`/questions/${capQ}`,'GET',undefined,capActor)).status,200); // More than 100 ownership bind variables must be chunked.
const concurrentActor=actor('concurrent');
const createTwice=await Promise.all([post('/api/v1/tips',tipInput,concurrentActor,'create-twice'),post('/api/v1/tips',tipInput,concurrentActor,'create-twice')]);
assert.equal(createTwice[0].data.id,createTwice[1].data.id);
const different=await Promise.all([request('/api/v1/tips','POST',{...tipInput,title:'Concurrent content variation one'},{...concurrentActor,'Idempotency-Key':'create-conflict'}),request('/api/v1/tips','POST',{...tipInput,title:'Concurrent content variation two'},{...concurrentActor,'Idempotency-Key':'create-conflict'})]);
assert.deepEqual(different.map(r=>r.status).sort(),[201,409]);
assert.equal((await request('/api/v1/tips','POST',tipInput,{...concurrentActor,'Idempotency-Key':'create-conflict'})).status,409);
for(let n=0;n<4;n++){
 const qa=actor('race-question-'+n),aa=actor('race-answer-'+n);
 const raceQ=(await post('/api/v1/questions',question,qa)).data;
 const raceA=(await post(`/api/v1/questions/${raceQ.id}/answers`,{body:'Answer for the acceptance withdrawal race.'},aa)).data;
 const [accept,withdraw]=await Promise.all([request(`/api/v1/questions/${raceQ.id}/acceptance`,'POST',{answer_id:raceA.id},qa),request(`/api/v1/posts/${raceA.id}`,'DELETE',undefined,aa)]);
 assert.ok([200,404,409].includes(accept.status),JSON.stringify(accept));assert.equal(withdraw.status,200);
 const raceDetail=(await request(`/api/v1/questions/${raceQ.id}`)).data.data;
 assert.equal(raceDetail.resolved,false);assert.equal(raceDetail.accepted_answer_id,null);assert.equal(raceDetail.resolved_at,null);assert.equal(raceDetail.answers.length,0);
}
// Legacy fixture was inserted without receipts, as by the old application.
const legacyId='q_11111111-1111-4111-8111-111111111111',legacyActor={'oai-authenticated-user-id':'legacy-owner','oai-authenticated-user-email':'legacy@example.test'};
const legacy=await request('/api/v1/questions/'+legacyId);assert.equal(legacy.status,200);assert.equal(legacy.data.data.body,'Legacy original body, unchanged.');assert.equal(legacy.data.data.resolved,false);assert.deepEqual(legacy.data.data.updates,[]);
assert.equal((await post('/api/v1/questions',{title:'Legacy original question',body:'Legacy original body, unchanged.',tags:['legacy'],author_label:'legacy-label'},legacyActor,'legacy-request-key')).data.id,legacyId);
assert.equal((await request(`/api/v1/posts/${legacyId}/updates`,'POST',historyBody,{...legacyActor,'Idempotency-Key':'legacy-request-key'})).status,409);
const legacyAnswer=(await post(`/api/v1/questions/${legacyId}/answers`,{body:'Legacy question accepts a new self-answer.'},legacyActor)).data;
await post(`/api/v1/questions/${legacyId}/acceptance`,{answer_id:legacyAnswer.id},legacyActor,null,200);
await post(`/api/v1/posts/${legacyId}/updates`,{body:'Legacy author can append while preserving original history.'},legacyActor);
assert.equal((await request(`/api/v1/posts/${legacyId}`,'DELETE',undefined,legacyActor)).status,200);
assert.equal((await request('/api/v1/questions/'+legacyId)).status,404);
assert.equal((await request(`/api/v1/posts/${legacyAnswer.id}/updates`,'POST',historyBody,legacyActor)).status,404);
for(const publicData of [detail,td,discovery,openapi])for(const forbidden of ['author_key','enhancement-owner','@example.test'])assert.ok(!JSON.stringify(publicData).includes(forbidden));
fs.writeFileSync('.sites-runtime/enhancement-durability.json',JSON.stringify({question_id:q.id,accepted_answer_id:self.id,tip_id:tip.id,reply_id:reply.id,original:q.body}));
console.log('PASS: acceptance/reopening/self-answer/withdrawal, hash ownership, append-only history, concurrent retries, Tips & Tricks replies/search/tags, UI escaping and controls, REST/MCP/discovery, new-write rate limits and legacy routes/keys.');
