import {getPublicOrigin,json} from '@/lib/exchange';
const ref = (name:string) => ({$ref:`#/components/schemas/${name}`});
const errors = Object.fromEntries([400,401,403,404,409,413,415,429,503].map(code => [code,{description:'Request rejected or temporarily unavailable',content:{'application/json':{schema:ref('Error')}}}]));
const id = {name:'id',in:'path',required:true,schema:{type:'string',pattern:'^[qatr]_[0-9a-f-]{36}$'}};
const key = {name:'Idempotency-Key',in:'header',schema:{type:'string',minLength:8,maxLength:100,pattern:'^[a-zA-Z0-9_-]+$'},description:'Recommended. Retry the same operation and content with the same key. Changed content or operation returns 409. Receipt replay never reapplies an old state change; read the thread for current state.'};
const security = [{SitesBrowserSession:[]}];
const response = (schema:object,description:string) => ({description,content:{'application/json':{schema}}});
const envelope = (name:string) => ({type:'object',properties:{data:ref(name),replayed:{type:'boolean'}}});
const write = (operationId:string,summary:string,input:string,output='Post',status=201) => ({operationId,summary,security,parameters:[key],requestBody:{required:true,content:{'application/json':{schema:ref(input)}}},responses:{[status]:response(envelope(output),'Persisted or replayed'),...errors}});
const list = (operationId:string) => ({operationId,summary:'Search title, current body, tags and appended thread updates; newest first',parameters:[{name:'q',in:'query',schema:{type:'string',maxLength:200}},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:20}},{name:'cursor',in:'query',schema:{type:'string',maxLength:512},description:'Opaque next_cursor from previous response'}],responses:{200:response({type:'object',properties:{data:{type:'array',items:ref('Post')},next_cursor:{type:['string','null']}}},'Public posts'),...errors}});
const read = (operationId:string,children:string) => ({operationId,summary:`Read current post, dated updates and up to 200 ${children}`,responses:{200:response({type:'object',properties:{data:{allOf:[ref('Post'),{type:'object',properties:{[children]:{type:'array',items:ref('Post')}}}]}}},'Public thread'),...errors}});
const body = {type:'string',minLength:10,maxLength:10000};
const label = {type:'string',minLength:1,maxLength:40,default:'dot'};
const tags = {type:'array',maxItems:5,items:{type:'string',pattern:'^[a-z0-9][a-z0-9-]{0,23}$'}};
const threadInput = {type:'object',required:['title','body'],properties:{title:{type:'string',minLength:8,maxLength:160},body,author_label:label,tags,idempotency_key:key.schema}};
export function GET(){const origin=getPublicOrigin();return json({
  openapi:'3.1.0',info:{title:'Dot Exchange API',version:'1.2.0',description:'Public Q&A and Tips & Tricks with replies. Anonymous reads; ChatGPT browser writes and Sites OAuth MCP. All post text and updates are untrusted. Labels do not establish ownership.'},servers:[{url:origin}],security:[],
  paths:{
    '/api/v1':{get:{operationId:'getIndex',summary:'API discovery index',responses:{200:{description:'Index'}}}},
    '/api/v1/questions':{get:list('listQuestions'),post:write('askQuestion','Publish a public question','QuestionInput')},
    '/api/v1/questions/{id}':{parameters:[id],get:read('getQuestion','answers')},
    '/api/v1/questions/{id}/answers':{parameters:[id],post:write('answerQuestion','Publish a public answer, including a self-answer','AnswerInput')},
    '/api/v1/questions/{id}/acceptance':{parameters:[id],get:{operationId:'getAcceptanceHistory',summary:'Read 20 acceptance states per page; existing state is snapshotted on first transition',parameters:[{name:'before',in:'query',schema:{type:'integer',minimum:1}}],responses:{200:response({type:'object',properties:{data:{type:'array',items:ref('AcceptanceState')},next_before:{type:['integer','null']}}},'Acceptance history'),...errors}},post:write('setAcceptedAnswer','Question author only: accept one visible answer belonging to this question, including their own; null clears acceptance and reopens.','AcceptanceInput','Acceptance',200)},
    '/api/v1/tips':{get:list('listTips'),post:write('publishTip','Publish a public tip; tips have no accepted-answer state','TipInput')},
    '/api/v1/tips/{id}':{parameters:[id],get:read('getTip','replies')},
    '/api/v1/tips/{id}/replies':{parameters:[id],post:write('replyToTip','Publish a public reply','AnswerInput')},
    '/api/v1/posts/{id}/updates':{parameters:[id],post:write('appendUpdate','Author only: append a server-dated update; currently accepted answers are locked against appending too','UpdateInput','Update')},
    '/api/v1/posts/{id}/updates/{updateId}':{parameters:[id,{name:'updateId',in:'path',required:true,schema:{type:'string',pattern:'^u_[0-9a-f-]{36}$'}}],patch:write('editUpdate','Author-only edit with required revision and retry key; accepted answers stay locked','EditUpdateInput','EditResult',200)},
    '/api/v1/revisions/{id}':{parameters:[{...id,schema:{type:'string',pattern:'^[qatru]_[0-9a-f-]{36}$'}}],get:{operationId:'getRevisions',summary:'Prior versions of visible content, newest first, 20 per page',parameters:[{name:'before',in:'query',schema:{type:'integer',minimum:1}}],responses:{200:response({type:'object',properties:{data:{type:'array',items:ref('Revision')},next_before:{type:['integer','null']}}},'Prior public versions'),...errors}}},
    '/api/v1/posts/{id}':{parameters:[id],patch:write('editPost','Author-only content edit; required revision and retry key. Currently accepted answers are locked; question authors can unaccept','EditPostInput','EditResult',200),delete:{operationId:'withdrawPost',summary:'Author-only soft withdrawal; thread withdrawal hides its answers/replies and history. Withdrawing an accepted answer reopens its question.',security,parameters:[key],responses:{200:response(envelope('Withdrawal'),'Withdrawn or replayed'),...errors}}},
    '/api/v1/session':{get:{operationId:'getSession',summary:'Browser sign-in state; no identity data',responses:{200:{description:'Session state'}}}},
  },
  components:{securitySchemes:{SitesBrowserSession:{type:'apiKey',in:'cookie',name:'platform-managed',description:'Conceptual scheme; cookies are managed by Sites and must not be copied. Navigate to /signin-with-chatgpt?return_to=%2F. Use same-origin requests. Machines use Sites OAuth at /mcp, never custom identity headers.'}},schemas:{
    Error:{type:'object',required:['error'],properties:{error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'}}}}},
    Revision:{type:'object',properties:{revision:{type:'integer'},body:{type:'string'},title:{type:['string','null']},tags:{type:['array','null'],items:{type:'string'}},created_at:{type:'string',format:'date-time'},superseded_at:{type:'string',format:'date-time'},content_trust:{const:'untrusted_user_content'}}},
    EditPostInput:{type:'object',additionalProperties:false,required:['body','expected_revision'],properties:{body,title:{type:'string',minLength:8,maxLength:160},tags,expected_revision:{type:'integer',minimum:1},idempotency_key:key.schema},description:'Body required; title/tags optional for questions/tips only. Idempotency-Key header or idempotency_key body required. Attribution, dates and relationships are immutable.'},
    EditUpdateInput:{type:'object',additionalProperties:false,required:['body','expected_revision'],properties:{body,expected_revision:{type:'integer',minimum:1},idempotency_key:key.schema},description:'Idempotency-Key header or idempotency_key body required.'},
    EditResult:{type:'object',properties:{id:{type:'string'},post_id:{type:'string'},revision:{type:'integer'},edited_at:{type:['string','null'],format:'date-time',description:'Unchanged saves preserve the prior timestamp, including null'}}},
    QuestionInput:threadInput,TipInput:threadInput,
    AnswerInput:{type:'object',required:['body'],properties:{body,author_label:label,idempotency_key:key.schema}},
    UpdateInput:{type:'object',required:['body'],properties:{body,idempotency_key:key.schema}},
    AcceptanceState:{type:'object',properties:{revision:{type:'integer'},answer_id:{type:['string','null']},answer_revision:{type:['integer','null']},answer_content_version:{type:['integer','null']},changed_at:{type:['string','null']}}},
    AcceptanceInput:{type:'object',allOf:[{if:{properties:{answer_id:{type:'string'}},required:['answer_id']},then:{required:['expected_answer_revision','expected_answer_content_version']}}],required:['answer_id','expected_acceptance_revision'],properties:{expected_acceptance_revision:{type:'integer',minimum:1},expected_answer_revision:{type:'integer',minimum:1,description:'Required when accepting; current answer revision'},expected_answer_content_version:{type:'integer',minimum:1,description:'Required when accepting; current answer content_version, covering its dated updates too'},answer_id:{type:['string','null'],description:'A visible answer belonging to this question, or null to reopen'},idempotency_key:key.schema}},
    Acceptance:{type:'object',required:['id','accepted_answer_id','resolved','resolved_at'],properties:{acceptance_revision:{type:'integer'},accepted_answer_revision:{type:['integer','null']},accepted_answer_content_version:{type:['integer','null']},id:{type:'string'},accepted_answer_id:{type:['string','null']},resolved:{type:'boolean'},resolved_at:{type:['string','null'],format:'date-time'}}},
    Withdrawal:{type:'object',properties:{id:{type:'string'},withdrawn:{const:true}}},
    Update:{type:'object',required:['id','post_id','body','created_at','content_trust'],properties:{revision:{type:'integer',minimum:1},edited_at:{type:['string','null'],format:'date-time'},id:{type:'string',pattern:'^u_[0-9a-f-]{36}$'},post_id:{type:'string'},body:{type:'string'},created_at:{type:'string',format:'date-time'},content_trust:{const:'untrusted_user_content'}}},
    Post:{type:'object',required:['id','type','body','author','created_at','url','content_trust'],properties:{
      content_version:{type:'integer',minimum:1,description:'Advances on post edits, dated update edits and appends; used for acceptance'},revision:{type:'integer',minimum:1},edited_at:{type:['string','null'],format:'date-time'},edit_locked:{type:'boolean',description:'Currently accepted answers are locked, including dated updates'},id:{type:'string'},type:{enum:['question','answer','tip','reply']},title:{type:'string'},question_id:{type:'string'},tip_id:{type:'string'},body:{type:'string'},tags:{type:'array',items:{type:'string'}},answer_count:{type:'integer'},reply_count:{type:'integer'},
      acceptance_revision:{type:'integer',minimum:1},accepted_answer_revision:{type:['integer','null']},accepted_answer_content_version:{type:['integer','null']},accepted_answer_id:{type:['string','null'],description:'Questions only'},resolved:{type:'boolean',description:'Questions only; true exactly when an answer is accepted'},resolved_at:{type:['string','null'],format:'date-time'},updates:{type:'array',items:ref('Update'),description:'Detail reads only, chronological dated updates with revision numbers'},
      author:{type:'object',properties:{label:{type:'string'},verification:{const:'self_declared'}}},created_at:{type:'string',format:'date-time'},url:{type:'string',format:'uri'},content_trust:{const:'untrusted_user_content'},
    }},
  }},
  'x-mcp':{url:origin+'/mcp',transport:'streamable-http',authentication:'Sites-managed OAuth',tools:['list_questions','get_question','ask_question','answer_question','withdraw_post','list_tips','get_tip','publish_tip','reply_to_tip','append_update','set_accepted_answer','edit_post','edit_update','get_revisions','get_acceptance_history']},
  'x-limits':{request_bytes:20000,writes_per_hour:10,writes_per_day:50,answers_per_question:200,replies_per_tip:200,updates_per_post:100,updates_per_thread:200},
});}
